backend_default:
    resource: '@BackendBundle/Resources/config/route/default.yml'
    prefix: /
backend_user:
    resource: '@BackendBundle/Resources/config/route/user.yml'
    prefix: /user
backend_session:
    resource: '@BackendBundle/Resources/config/route/session.yml'
    prefix: /session
backend_gcm:
    resource: '@BackendBundle/Resources/config/route/gcm.yml'
    prefix: /gcm
backend_google:
    resource: '@BackendBundle/Resources/config/route/google.yml'
    prefix: /google
backend_googledrivesettings:
    resource: '@BackendBundle/Resources/config/route/googledrive-settings.yml'
    prefix: /google-drive-settings
backend_googledrive:
    resource: '@BackendBundle/Resources/config/route/googledrive.yml'
    prefix: /google-drive
backend_files:
    resource: '@BackendBundle/Resources/config/route/files.yml'
    prefix: /files
backend_acl:
    resource: '@BackendBundle/Resources/config/route/acl.yml'
    prefix: /acl
backend_assigngrouphasuser:
    resource: '@BackendBundle/Resources/config/route/assign-group-has-user.yml'
    prefix: /assign-group-has-user
backend_assigntemplatehasmodule:
    resource: '@BackendBundle/Resources/config/route/assign-template-has-module.yml'
    prefix: /assign-template-has-module
backend_categorytree:
    resource: '@BackendBundle/Resources/config/route/category-tree.yml'
    prefix: /category-tree
backend_categorytreetoassign:
    resource: '@BackendBundle/Resources/config/route/category-treetoassign.yml'
    prefix: /category-tree-to-assign
backend_template:
    resource: '@BackendBundle/Resources/config/route/template.yml'
    prefix: /template
backend_templatemodule:
    resource: '@BackendBundle/Resources/config/route/templatemodule.yml'
    prefix: /templatemodule
backend_assigncoursehasuserteacher:
    resource: '@BackendBundle/Resources/config/route/assign-course-has-user-teacher.yml'
    prefix: /assign-course-has-user-teacher
backend_assigncoursehasuserstudent:
    resource: '@BackendBundle/Resources/config/route/assign-course-has-user-student.yml'
    prefix: /assign-course-has-user-student
backend_registerattendanceteacher:
    resource: '@BackendBundle/Resources/config/route/register-attendance-teacher.yml'
    prefix: /register-attendance-teacher
backend_registerattendancestudent:
    resource: '@BackendBundle/Resources/config/route/register-attendance-student.yml'
    prefix: /register-attendance-student
backend_aclprofile:
    resource: '@BackendBundle/Resources/config/route/aclprofile.yml'
    prefix: /aclprofile
backend_aclrole:
    resource: '@BackendBundle/Resources/config/route/aclrole.yml'
    prefix: /aclrole
backend_client:
    resource: '@BackendBundle/Resources/config/route/client.yml'
    prefix: /client
backend_groupofusers:
    resource: '@BackendBundle/Resources/config/route/groupofusers.yml'
    prefix: /groupofusers
backend_pointofsale:
    resource: '@BackendBundle/Resources/config/route/pointofsale.yml'
    prefix: /pointofsale
backend_product:
    resource: '@BackendBundle/Resources/config/route/product.yml'
    prefix: /product
backend_course:
    resource: '@BackendBundle/Resources/config/route/course.yml'
    prefix: /course
backend_exam:
    resource: '@BackendBundle/Resources/config/route/exam.yml'
    prefix: /exam
backend_assigncoursehasexam:
    resource: '@BackendBundle/Resources/config/route/assign-course-has-exam.yml'
    prefix: /assign-course-has-exam
backend_registerexamgrade:
    resource: '@BackendBundle/Resources/config/route/register-exam-grade.yml'
    prefix: /register-exam-grade
backend_chart:
    resource: '@BackendBundle/Resources/config/route/chart.yml'
    prefix: /chart
backend_comparegrades:
    resource: '@BackendBundle/Resources/config/route/compare-grades.yml'
    prefix: /compare-grades
backend_test:
    resource: '@BackendBundle/Resources/config/route/test.yml'
    prefix: /test
backend_modulo_asistencia:
    resource: '@BackendBundle/Resources/config/route/modulo-asistencia.yml'
    prefix: /modulo-asistencia
backend_modulo_resultado:
    resource: '@BackendBundle/Resources/config/route/modulo-resultado.yml'
    prefix: /modulo-resultado
backend_chatbot:
    resource: '@BackendBundle/Resources/config/route/chatbot.yml'
    prefix: /chatbot
